#!/usr/bin/env bash

# PLEASE NOTE: This script has been automatically generated by conda-smithy. Any changes here
# will be lost next time ``conda smithy rerender`` is run. If you would like to make permanent
# changes to this script, consider a proposal to conda-smithy so that other feedstocks can also
# benefit from the improvement.
yum install -y wget openssh-clients bzip2
#wget https://repo.anaconda.com/archive/Anaconda3-5.1.0-Linux-x86_64.sh
#sh Anaconda3-5.1.0-Linux-x86_64.sh -b -p /opt/conda
#export PATH=$PATH:/opt/conda/bin/conda
echo $?
pwd
ls
pwd
sudo /opt/conda/bin/conda build recipe  || exit 1
